// File Generated by Assets/BuildShader.py - source: [PostEffectFS.d.hlsl : _]
Texture2D uTexColor : register(t0);
SamplerState uTexColorSampler : register(s0);
cbuffer cbPerFrame
{
	float2 uExposure;
};
struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float4 color : COLOR0;
	float2 tex0 : TEXCOORD0;
};
static const float gamma = 2.2;
static const float invGamma = 1.0 / 2.2;
float3 sRGB(float3 color)
{
	return pow(color, gamma);
}
float3 linearRGB(float3 color)
{
	return pow(color, invGamma);
}
float4 main(PS_INPUT input) : SV_TARGET
{
	float4 color = uTexColor.Sample(uTexColorSampler, input.tex0);
	float exposure = uExposure.x;
	return float4(linearRGB(exposure * color.rgb), color.a);
}
