// File Generated by Assets/BuildShader.py - source: [SGLitFS.d.glsl : INSTANCING,NO_NORMAL_MAP,NO_TEXTURE,POINTLIGHT]
precision mediump float;
precision highp sampler2D;
precision highp sampler2DArray;
uniform vec4 uLightColor;
uniform vec4 uColor;
uniform vec2 uLightMul;
uniform vec2 uSpecGloss;
uniform vec4 uCamPosition;
uniform vec4 uSHConst[4];
struct PointLight {
	vec4 Position;
	vec4 Attenuation;
	vec4 Direction;
	vec4 Color;
};
layout(std140) uniform uListLights
{
	PointLight Lights[200];
} LightData;
in vec2 vTexCoord0;
in vec4 vWorldPos;
in vec3 vWorldNormal;
in vec3 vWorldViewDir;
in vec3 vWorldLightDir;
in vec3 vWorldTangent;
in vec3 vWorldBinormal;
in float vTangentW;
flat in vec4 vLightIndex;
out vec4 FragColor;
const float gamma = 2.2;
const float invGamma = 1.0 / 2.2;
vec3 sRGB(vec3 color)
{
	return pow(color, vec3(gamma));
}
vec3 linearRGB(vec3 color)
{
	return pow(color, vec3(invGamma));
}
vec3 shAmbient(vec3 n)
{
	vec3 ambientLighting = uSHConst[0].xyz +
		uSHConst[1].xyz * n.y +
		uSHConst[2].xyz * n.z +
		uSHConst[3].xyz * n.x;
	return ambientLighting * 0.75;
}
vec3 pointlight(
	const vec3 position,
	const vec3 normal,
	const vec3 camPosition,
	const vec4 lightColor,
	const vec3 lightPosition,
	const vec4 lightAttenuation,
	const float spec,
	const float gloss,
	const vec3 specColor)
{
	vec3 direction = lightPosition - position;
	float distance = length(direction);
	float attenuation = max(0.0, 1.0 - (distance * lightAttenuation.y)) * lightColor.a;
	vec3 lightDir = normalize(direction);
	float NdotL = max(0.0, dot(lightDir, normal));
	vec3 v = camPosition - position;
	vec3 viewDir = normalize(v);
	vec3 H = normalize(direction + viewDir);
	float NdotE = max(0.0,dot(normal, H));
	float specular = pow(NdotE, 10.0 + 100.0 * gloss) * spec;
	return (lightColor.rgb * NdotL + specular * specColor) * attenuation;
}
const float PI = 3.1415926;
void main(void)
{
	vec4 diffuseMap = uColor;
	vec3 specMap = vec3(uSpecGloss, 1.0);
	vec3 n = vWorldNormal;
	vec3 ambientLighting = shAmbient(n);
	ambientLighting = sRGB(ambientLighting);
	vec3 diffuseColor = sRGB(diffuseMap.rgb);
	vec3 lightColor = sRGB(uLightColor.rgb);
	float spec = specMap.r;
	float gloss = specMap.g;
	vec3 specularColor = vec3(0.5, 0.5, 0.5);
	float NdotL = max(dot(n, vWorldLightDir), 0.0);
	vec3 directionalLight = NdotL * lightColor;
	PointLight light = LightData.Lights[int(vLightIndex.x)];
	directionalLight += pointlight(
		vWorldPos.xyz,
		n,
		uCamPosition.xyz,
		light.Color,
		light.Position.xyz,
		light.Attenuation,
		spec,
		gloss,
		specularColor);
	light = LightData.Lights[int(vLightIndex.y)];
	directionalLight += pointlight(
		vWorldPos.xyz,
		n,
		uCamPosition.xyz,
		light.Color,
		light.Position.xyz,
		light.Attenuation,
		spec,
		gloss,
		specularColor);
	vec3 color = directionalLight * diffuseColor * 0.3 * uLightMul.y;
	vec3 H = normalize(vWorldLightDir + vWorldViewDir);
	float NdotE = max(0.0, dot(n, H));
	float specular = pow(NdotE, 10.0 + 100.0 * gloss) * spec;
	color += specular * specularColor * uLightMul.x;
	color += ambientLighting * diffuseColor / PI;
	FragColor = vec4(color, diffuseMap.a);
}
