// File Generated by Assets/BuildShader.py - source: [ColorFS.glsl : INSTANCING]
precision highp float;
in vec2 vTexCoord0;
in vec4 vWorldPosition;
in vec3 vWorldNormal;
in float vTangentW;
in vec4 vColor;
in vec4 vSpecGloss;
layout(location = 0) out vec4 Diffuse;
layout(location = 1) out vec4 Position;
layout(location = 2) out vec4 Normal;
layout(location = 3) out vec4 SG;
void main(void)
{
	Diffuse = vColor;
	SG = vSpecGloss;
	Position = vWorldPosition;
	Normal = vec4(vWorldNormal, 1.0);
}
