// File Generated by Assets/BuildShader.py - source: [DiffuseFS.glsl : INSTANCING]
precision highp float;
uniform sampler2D uTexDiffuse;
in vec4 vColor;
in vec2 vSpecGloss;
in vec2 vTexCoord0;
in vec4 vWorldPosition;
in vec3 vWorldNormal;
in float vTangentW;
layout(location = 0) out vec4 Diffuse;
layout(location = 1) out vec4 Position;
layout(location = 2) out vec4 Normal;
layout(location = 3) out vec4 SG;
void main(void)
{
	vec3 baseMap = texture(uTexDiffuse, vTexCoord0.xy).rgb ;
	Diffuse = vec4(baseMap * vColor.rgb, 1.0);
	Position = vWorldPosition;
	Normal = vec4(vWorldNormal, 1.0);
	SG = vec4(vSpecGloss.x, vSpecGloss.y, 1.0, 1.0);
}
