// File Generated by Assets/BuildShader.py - source: [SpecularGlossinessVS.glsl : INSTANCING]
layout(location = 0) in vec4 inPosition;
layout(location = 1) in vec3 inNormal;
layout(location = 2) in vec4 inColor;
layout(location = 3) in vec2 inTexCoord0;
layout(location = 4) in vec3 inTangent;
layout(location = 5) in vec3 inBinormal;
layout(location = 6) in vec2 inData;
layout(location = 7) in vec4 uUVScale;
layout(location = 8) in vec4 uColor;
layout(location = 9) in vec4 uSpecGloss;
layout(location = 10) in mat4 uWorldMatrix;
uniform mat4 uVPMatrix;
uniform mat4 uView;
out vec3 vWorldNormal;
out vec4 vWorldPosition;
out vec3 vWorldTangent;
out vec3 vWorldBinormal;
out vec2 vTexCoord0;
out float vTangentW;
out vec4 vColor;
out vec2 vSpecGloss;
void main(void)
{
	vColor = uColor;
	vSpecGloss = uSpecGloss.xy;
	mat4 uMvpMatrix = uVPMatrix * uWorldMatrix;
	vWorldPosition = uWorldMatrix*inPosition;
	vec4 sampleFragPos = uView * vWorldPosition;
	vWorldPosition.w = sampleFragPos.z;
	vec4 worldNormal = uWorldMatrix * vec4(inNormal, 0.0);
	vec4 worldTangent = uWorldMatrix * vec4(inTangent, 0.0);
	vWorldNormal = normalize(worldNormal.xyz);
	vWorldTangent = normalize(worldTangent.xyz);
	vWorldBinormal = normalize(cross(vWorldNormal.xyz, vWorldTangent.xyz));
	vTexCoord0 = inTexCoord0 * uUVScale.xy + uUVScale.zw;
	vTangentW = inData.x;
	gl_Position = uMvpMatrix * inPosition;
}
