// File Generated by Assets/BuildShader.py - source: [ReflectionProbeFS.d.glsl : _]
precision highp float;
uniform samplerCube uTexReflect;
in vec4 vColor;
in vec3 vWorldNormal;
out vec4 FragColor;
const float gamma = 2.2;
const float invGamma = 1.0 / 2.2;
vec3 sRGB(vec3 color)
{
	return pow(color, vec3(gamma));
}
vec3 linearRGB(vec3 color)
{
	return pow(color, vec3(invGamma));
}
void main(void)
{
	FragColor = vec4(sRGB(textureLod(uTexReflect, vWorldNormal, 0.0).rgb), 1.0);
}
