// File Generated by Assets/BuildShader.py - source: [EmissiveFS.d.hlsl : _]
struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float4 color : COLOR0;
};
cbuffer cbPerFrame
{
	float4 uColor;
	float4 uEmissive;
};
static const float gamma = 2.2;
static const float invGamma = 1.0 / 2.2;
float3 sRGB(float3 color)
{
	return pow(color, gamma);
}
float3 linearRGB(float3 color)
{
	return pow(color, invGamma);
}
float4 main(PS_INPUT input) : SV_TARGET
{
	float3 color = sRGB(input.color.rgb * uColor.rgb) * uEmissive.rgb * uEmissive.a;
	return float4(color, 1.0);
}
