option(BUILD_IMGUI "Build Ocornut Imgui" ON)
option(BUILD_FREETYPE "Build freetype font library" ON)
option(BUILD_SKYLICHT_AUDIO "Build with audio engine" ON)
option(BUILD_SKYLICHT_COMPONENTS "Build with components" ON)
option(BUILD_SKYLICHT_LIGHMAPPER "Build with lightmapper" ON)
option(BUILD_SKYLICHT_COLLISION "Build with collision" ON)
option(BUILD_SKYLICHT_UI "Build with user interface" ON)
option(BUILD_SKYLICHT_CRYPTO "Build with crypto (md5, sha246, base64)" ON)
option(BUILD_SKYLICHT_NETWORK "Build with Http, Socket module" ON)
option(BUILD_BULLET_PHYSIC_LIB "Build bullet physic" ON)
option(BUILD_SKYLICHT_PHYSIC "Build with physic engine" ON)
option(BUILD_EXAMPLES "Build example projects" ON)