option(BUILD_IMGUI "Build Ocornut Imgui" ON)
option(BUILD_FREETYPE "Build freetype font library" ON)
option(BUILD_SKYLICHT_AUDIO "Build Skylicht with audio support" ON)
option(BUILD_SKYLICHT_COMPONENTS "Build Skylicht components" ON)
option(BUILD_SKYLICHT_LIGHMAPPER "Build Skylicht lightmapper" ON)
option(BUILD_SKYLICHT_COLLISION "Build Skylicht collision" ON)
option(BUILD_SKYLICHT_UI "Build Skylicht user interface" ON)
option(BUILD_SKYLICHT_CRYPTO "Build Skylicht with crypto (md5, sha246, base64)" ON)
option(BUILD_SKYLICHT_NETWORK "Build Skylicht with Http, Socket module" ON)
option(BUILD_BULLET_PHYSIC_LIB "Build bullet physic" ON)
option(BUILD_SKYLICHT_PHYSICS "Build Skylicht physic" ON)
option(BUILD_EXAMPLES "Build example projects" ON)