python Scripts\update_cmake.py SampleAnimations Samples\Animations
python Scripts\update_cmake.py SampleAudio Samples\Audio
python Scripts\update_cmake.py SampleBlendShape Samples\BlendShape
python Scripts\update_cmake.py SampleBoidSystem Samples\BoidSystem
python Scripts\update_cmake.py SampleBoidSystemVAT Samples\BoidSystemVAT
python Scripts\update_cmake.py SampleCharacterController Samples\CharacterController
python Scripts\update_cmake.py SampleCollision Samples\Collision
python Scripts\update_cmake.py SampleDrawPrimitives Samples\DrawPrimitives
python Scripts\update_cmake.py SampleGraph Samples\Graph
python Scripts\update_cmake.py SampleGUI Samples\GUI
python Scripts\update_cmake.py SampleHelloWorld Samples\HelloWorld
python Scripts\update_cmake.py SampleHttpRequest Samples\HttpRequest
python Scripts\update_cmake.py SampleInstancing Samples\Instancing
python Scripts\update_cmake.py SampleLightmap Samples\Lightmap
python Scripts\update_cmake.py SampleLightmapping Samples\Lightmapping
python Scripts\update_cmake.py SampleLightmappingDirectional Samples\LightmappingDirectional
python Scripts\update_cmake.py SampleLightmappingVertex Samples\LightmappingVertex
python Scripts\update_cmake.py SampleLightmapUV Samples\LightmapUV
python Scripts\update_cmake.py SampleLoadScene Samples\LoadScene
python Scripts\update_cmake.py SampleLuckyDraw Samples\LuckyDraw
python Scripts\update_cmake.py SampleMaterials Samples\Materials
python Scripts\update_cmake.py SampleNoise2D Samples\Noise2D
python Scripts\update_cmake.py SampleNoise3D Samples\Noise3D
python Scripts\update_cmake.py SampleOcclusionQuery Samples\OcclusionQuery
python Scripts\update_cmake.py SampleParticles Samples\Particles
python Scripts\update_cmake.py SampleParticlesExplosion Samples\ParticlesExplosion
python Scripts\update_cmake.py SampleParticlesMagicSkill Samples\ParticlesMagicSkill
python Scripts\update_cmake.py SampleParticlesVortex Samples\ParticlesVortex
python Scripts\update_cmake.py SamplePBR Samples\PBR
python Scripts\update_cmake.py SamplePhysics Samples\Physics
python Scripts\update_cmake.py SampleShader Samples\Shader
python Scripts\update_cmake.py SampleSkinnedMesh Samples\SkinnedMesh
python Scripts\update_cmake.py SampleSkinnedMeshInstancing Samples\SkinnedMeshInstancing
python Scripts\update_cmake.py SampleSocketIO Samples\SocketIO
python Scripts\update_cmake.py SampleSpine2D Samples\Spine2D
python Scripts\update_cmake.py SampleSponza Samples\Sponza
python Scripts\update_cmake.py SampleSpringBone Samples\SpringBone
python Scripts\update_cmake.py SampleTankScene Samples\TankScene
python Scripts\update_cmake.py SampleWalkIK Samples\WalkIK