// File Generated by Assets/BuildShader.py - source: [SkinToonInstancing2VS.d.hlsl : _]
Texture2D uTransformTexture : register(t4);
SamplerState uTransformTextureSampler : register(s4);
struct VS_INPUT
{
	float4 pos: POSITION;
	float3 norm: NORMAL;
	float4 color: COLOR;
	float2 tex0: TEXCOORD0;
	float3 tangent : TANGENT;
	float3 binormal : BINORMAL;
	float2 data : DATA;
	float4 blendIndex : BLENDINDICES;
	float4 blendWeight : BLENDWEIGHT;
	float4 uBoneLocation: TEXCOORD1;
	float4 uColor: TEXCOORD2;
	float2 uBlendAnimation: TEXCOORD3;
	float4x4 worldMatrix: TEXCOORD4;
};
struct VS_OUTPUT
{
	float4 pos : SV_POSITION;
	float2 tex0 : TEXCOORD0;
	float3 worldNormal: WORLDNORMAL;
	float3 worldViewDir: WORLDVIEWDIR;
	float3 worldPos: WORLDPOSITION;
	float3 depth: DEPTH;
	float4 color: COLOR;
};
cbuffer cbPerObject
{
	float4x4 uVpMatrix;
	float4 uCameraPosition;
	float2 uBoneCount;
	float2 uTransformTextureSize;
};
float4x4 getTransformFromTexture(float2 p)
{
	float centerX = 0.5 / uTransformTextureSize.x;
	float centerY = 0.5 / uTransformTextureSize.y;
	float nextPixelX = 1.0 / uTransformTextureSize.x;
	float nextPixelY = 1.0 / uTransformTextureSize.y;
	float2 uv = float2(
		p.x * nextPixelX * 4.0 + centerX,
		p.y * nextPixelY + centerY
	);
	float4 c1 = uTransformTexture.SampleLevel(uTransformTextureSampler, uv, 0.0);
	uv.x = uv.x + nextPixelX;
	float4 c2 = uTransformTexture.SampleLevel(uTransformTextureSampler, uv, 0.0);
	uv.x = uv.x + nextPixelX;
	float4 c3 = uTransformTexture.SampleLevel(uTransformTextureSampler, uv, 0.0);
	uv.x = uv.x + nextPixelX;
	float4 c4 = uTransformTexture.SampleLevel(uTransformTextureSampler, uv, 0.0);
	uv.x = uv.x + nextPixelX;
	return float4x4(c1, c2, c3, c4);
}
VS_OUTPUT main(VS_INPUT input)
{
	VS_OUTPUT output;
	float4x4 uWorldMatrix = transpose(input.worldMatrix);
	float4x4 skinMatrix;
	float4 skinPosition1;
	float4 skinNormal1;
	float4 skinPosition2;
	float4 skinNormal2;
	float2 boneLocation = input.uBoneLocation.xy;
	float boneLocationY = input.uBoneLocation.y * uBoneCount.x;
	boneLocation.y = boneLocationY + input.blendIndex[0];
	skinMatrix = input.blendWeight[0] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[1];
	skinMatrix += input.blendWeight[1] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[2];
	skinMatrix += input.blendWeight[2] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[3];
	skinMatrix += input.blendWeight[3] * getTransformFromTexture(boneLocation);
	skinPosition1 = mul(input.pos, skinMatrix);
	skinNormal1 = mul(float4(input.norm, 0.0), skinMatrix);
	boneLocation = input.uBoneLocation.zw;
	boneLocationY = input.uBoneLocation.w * uBoneCount.x;
	boneLocation.y = boneLocationY + input.blendIndex[0];
	skinMatrix = input.blendWeight[0] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[1];
	skinMatrix += input.blendWeight[1] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[2];
	skinMatrix += input.blendWeight[2] * getTransformFromTexture(boneLocation);
	boneLocation.y = boneLocationY + input.blendIndex[3];
	skinMatrix += input.blendWeight[3] * getTransformFromTexture(boneLocation);
	skinPosition2 = mul(input.pos, skinMatrix);
	skinNormal2 = mul(float4(input.norm, 0.0), skinMatrix);
	float4 skinPosition = lerp(skinPosition1, skinPosition2, input.uBlendAnimation.x);
	float4 skinNormal = lerp(skinNormal1, skinNormal2, input.uBlendAnimation.x);
	float4 worldPos = mul(skinPosition, uWorldMatrix);
	float4 worldNormal = mul(float4(skinNormal.xyz, 0.0), uWorldMatrix);
	output.worldPos = worldPos.xyz;
	output.depth = uCameraPosition.xyz - worldPos.xyz;
	output.worldViewDir = normalize(output.depth);
	output.pos = mul(worldPos, uVpMatrix);
	output.tex0 = input.tex0;
	output.worldNormal = normalize(worldNormal.xyz);
	output.color = input.color * input.uColor;
	return output;
}
