/*
!@
MIT License

Copyright (c) 2020 Skylicht Technology CO., LTD

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
(the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

This file is part of the "Skylicht Engine".
https://github.com/skylicht-lab/skylicht-engine
!#
*/

#include "pch.h"
#include "CParticleBufferData.h"
#include "CParticleRenderer.h"
#include "CParticleComponent.h"

#include "GameObject/CGameObject.h"
#include "Entity/CEntityManager.h"

#include "Culling/CCullingData.h"
#include "Culling/CCullingBBoxData.h"
#include "Transform/CWorldInverseTransformData.h"

namespace Skylicht
{
	namespace Particle
	{
		ACTIVATOR_REGISTER(CParticleComponent);

		CATEGORY_COMPONENT(CParticleComponent, "Particle", "Particle");

		CParticleComponent::CParticleComponent() :
			m_data(NULL)
		{

		}

		CParticleComponent::~CParticleComponent()
		{
			if (m_gameObject)
				m_gameObject->getEntity()->removeData<CParticleBufferData>();
		}

		void CParticleComponent::initComponent()
		{
			CEntity* entity = m_gameObject->getEntity();

			// add particle buffer data
			m_data = entity->addData<CParticleBufferData>();

			// add culling
			entity->addData<CCullingData>();
			entity->addData<CCullingBBoxData>();

			// add renderer system
			m_gameObject->getEntityManager()->addRenderSystem<CParticleRenderer>();
		}

		void CParticleComponent::startComponent()
		{
			if (!m_sourcePath.empty())
			{
				load();
			}
		}

		void CParticleComponent::updateComponent()
		{

		}

		CObjectSerializable* CParticleComponent::createSerializable()
		{
			CObjectSerializable* object = CComponentSystem::createSerializable();
			object->autoRelease(new CFilePathProperty(object, "source", m_sourcePath.c_str(), ".particle"));
			return object;
		}

		void CParticleComponent::loadSerializable(CObjectSerializable* object)
		{
			CComponentSystem::loadSerializable(object);
			m_sourcePath = object->get<std::string>("source", "");
		}

		bool CParticleComponent::save()
		{
			io::IXMLWriter* writeFile = getIrrlichtDevice()->getFileSystem()->createXMLWriter(m_sourcePath.c_str());
			if (writeFile == NULL)
				return false;

			writeFile->writeXMLHeader();
			writeFile->writeComment(L"File generated by function CParticleComponent::save");
			writeFile->writeLineBreak();

			CObjectSerializable* object = createSerializable();

			CObjectSerializable* groups = new CObjectSerializable("Groups");
			object->addProperty(groups);
			object->autoRelease(groups);

			saveGroups(groups);

			object->save(writeFile);
			delete object;

			writeFile->drop();
			return true;
		}

		void CParticleComponent::saveGroups(CObjectSerializable* groups)
		{
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
			{
				CGroup* group = m_data->Groups[i];
				CObjectSerializable* object = group->createSerializable();

				saveGroup(group, object);

				groups->addProperty(object);
				groups->autoRelease(object);
			}
		}

		void CParticleComponent::saveGroup(CGroup* group, CObjectSerializable* object)
		{
			CObjectSerializable* emitters = new CObjectSerializable("Emitters");
			object->addProperty(emitters);
			object->autoRelease(emitters);

			for (CEmitter* emitter : group->getEmitters())
			{
				CObjectSerializable* emitterData = emitter->createSerializable();
				emitters->addProperty(emitterData);
				emitters->autoRelease(emitterData);


				CObjectSerializable* zone = new CObjectSerializable("Zone");
				emitterData->addProperty(zone);
				emitterData->autoRelease(zone);

				if (emitter->getZone())
				{
					CObjectSerializable* zoneData = emitter->getZone()->createSerializable();
					zone->addProperty(zoneData);
					zone->autoRelease(zoneData);
				}
			}

			CObjectSerializable* models = new CObjectSerializable("Models");
			object->addProperty(models);
			object->autoRelease(models);

			for (CModel* model : group->getModels())
			{
				CObjectSerializable* emitterData = model->createSerializable();
				models->addProperty(emitterData);
				models->autoRelease(emitterData);
			}

			CObjectSerializable* renderer = new CObjectSerializable("Renderer");
			object->addProperty(renderer);
			object->autoRelease(renderer);

			if (group->getRenderer())
			{
				CObjectSerializable* rendererData = group->getRenderer()->createSerializable();
				renderer->addProperty(rendererData);
				renderer->autoRelease(rendererData);
			}
		}

		bool CParticleComponent::load()
		{
			io::IXMLReader* reader = getIrrlichtDevice()->getFileSystem()->createXMLReader(m_sourcePath.c_str());
			if (reader == NULL)
				return false;

			std::wstring nodeName = L"node";
			std::wstring attributeName;

			m_data->clear();

			CGroup* group = NULL;

			while (reader->read())
			{
				switch (reader->getNodeType())
				{
				case io::EXN_ELEMENT:
					if (nodeName == reader->getNodeName())
					{
						if (reader->getAttributeValue(L"type") != NULL)
						{
							attributeName = reader->getAttributeValue(L"type");

							if (attributeName == L"CParticleComponent")
							{
								CObjectSerializable* data = createSerializable();
								data->parseSerializable(reader);
								loadSerializable(data);
								delete data;
							}
							else if (attributeName == L"CGroup")
							{
								group = m_data->createGroup();
								CObjectSerializable* data = group->createSerializable();
								data->parseSerializable(reader);
								group->loadSerializable(data);
								delete data;
							}
							else if (attributeName == L"Emitters")
							{
								if (group)
									loadEmitters(group, reader);
							}
							else if (attributeName == L"Models")
							{
								if (group)
									loadModels(group, reader);
							}
							else if (attributeName == L"Renderer")
							{
								if (group)
									loadRenderer(group, reader);
							}
						}
					}
					break;
				default:
					break;
				}
			}

			reader->drop();
			return false;
		}

		void CParticleComponent::loadEmitters(CGroup* group, io::IXMLReader* reader)
		{
			std::wstring nodeName = L"node";
			std::wstring attributeName;
			int pos = 1;

			CEmitter* emitter = NULL;
			CZone* zone = NULL;
			CFactory* factory = getParticleFactory();

			while (reader->read())
			{
				switch (reader->getNodeType())
				{
				case io::EXN_ELEMENT:
					if (nodeName == reader->getNodeName())
					{
						pos++;
						if (reader->getAttributeValue(L"type") != NULL)
						{
							attributeName = reader->getAttributeValue(L"type");

							if (!emitter)
							{
								if (attributeName == L"CNormalEmitter")
									emitter = factory->createNormalEmitter(false);
								else if (attributeName == L"CRandomEmitter")
									emitter = factory->createRandomEmitter();
								else if (attributeName == L"CSphericEmitter")
									emitter = factory->createSphericEmitter(Transform::Oy, 0.0f, 45.0f * core::DEGTORAD);
								else if (attributeName == L"CStraightEmitter")
									emitter = factory->createStraightEmitter(Transform::Oy);

								if (emitter)
								{
									group->addEmitter(emitter);

									CObjectSerializable* data = emitter->createSerializable();
									data->parseSerializable(reader);
									emitter->loadSerializable(data);
									delete data;
								}
							}
							else
							{
								if (attributeName == L"CAABox")
									zone = factory->createZone(AABox);
								else if (attributeName == L"CCylinder")
									zone = factory->createZone(Cylinder);
								else if (attributeName == L"CLine")
									zone = factory->createZone(Line);
								else if (attributeName == L"CPoint")
									zone = factory->createZone(Point);
								else if (attributeName == L"CPolyLine")
									zone = factory->createZone(PolyLine);
								else if (attributeName == L"CRing")
									zone = factory->createZone(Ring);
								else if (attributeName == L"CSphere")
									zone = factory->createZone(Sphere);

								if (zone)
								{
									emitter->setZone(zone);

									CObjectSerializable* data = zone->createSerializable();
									data->parseSerializable(reader);
									zone->loadSerializable(data);
									delete data;
								}
							}
						}
					}
					break;
				case io::EXN_ELEMENT_END:
					if (nodeName == reader->getNodeName())
						pos--;

					if (pos == 0)
						return;

					break;
				}
			}
		}

		void CParticleComponent::loadModels(CGroup* group, io::IXMLReader* reader)
		{
			std::wstring nodeName = L"node";
			std::wstring attributeName;
			int pos = 1;

			CFactory* factory = getParticleFactory();

			while (reader->read())
			{
				switch (reader->getNodeType())
				{
				case io::EXN_ELEMENT:
					if (nodeName == reader->getNodeName())
					{
						pos++;
						if (reader->getAttributeValue(L"type") != NULL)
						{
							attributeName = reader->getAttributeValue(L"type");

							EParticleParams createParam = EParticleParams::NumParams;

							if (attributeName == L"Scale")
								createParam = EParticleParams::Scale;
							else if (attributeName == L"ScaleX")
								createParam = EParticleParams::ScaleX;
							else if (attributeName == L"ScaleY")
								createParam = EParticleParams::ScaleY;
							else if (attributeName == L"ScaleZ")
								createParam = EParticleParams::ScaleZ;
							else if (attributeName == L"RotateX")
								createParam = EParticleParams::RotateX;
							else if (attributeName == L"RotateY")
								createParam = EParticleParams::RotateY;
							else if (attributeName == L"RotateZ")
								createParam = EParticleParams::RotateZ;
							else if (attributeName == L"ColorR")
								createParam = EParticleParams::ColorR;
							else if (attributeName == L"ColorG")
								createParam = EParticleParams::ColorG;
							else if (attributeName == L"ColorB")
								createParam = EParticleParams::ColorB;
							else if (attributeName == L"ColorA")
								createParam = EParticleParams::ColorA;
							else if (attributeName == L"Mass")
								createParam = EParticleParams::Mass;
							else if (attributeName == L"FrameIndex")
								createParam = EParticleParams::FrameIndex;
							else if (attributeName == L"RotateSpeedX")
								createParam = EParticleParams::RotateSpeedX;
							else if (attributeName == L"RotateSpeedY")
								createParam = EParticleParams::RotateSpeedY;
							else if (attributeName == L"RotateSpeedZ")
								createParam = EParticleParams::RotateSpeedZ;

							if (createParam != EParticleParams::NumParams)
							{
								CModel* model = group->createModel(createParam);

								CObjectSerializable* data = model->createSerializable();
								data->parseSerializable(reader);
								model->loadSerializable(data);
								delete data;
							}
						}
					}
					break;
				case io::EXN_ELEMENT_END:
					if (nodeName == reader->getNodeName())
						pos--;

					if (pos == 0)
						return;

					break;
				}
			}
		}

		void CParticleComponent::loadRenderer(CGroup* group, io::IXMLReader* reader)
		{
			std::wstring nodeName = L"node";
			std::wstring attributeName;
			int pos = 1;

			CFactory* factory = getParticleFactory();

			while (reader->read())
			{
				switch (reader->getNodeType())
				{
				case io::EXN_ELEMENT:
					if (nodeName == reader->getNodeName())
					{
						pos++;
						if (reader->getAttributeValue(L"type") != NULL)
						{
							attributeName = reader->getAttributeValue(L"type");

							IRenderer* renderer = NULL;

							if (attributeName == L"CQuadRenderer")
								renderer = factory->createQuadRenderer();
							else if (attributeName == L"CBillboardAdditiveRenderer")
								renderer = factory->createBillboardAdditiveRenderer();

							if (renderer)
							{
								group->setRenderer(renderer);

								CObjectSerializable* data = renderer->createSerializable();
								data->parseSerializable(reader);
								renderer->loadSerializable(data);
								delete data;
							}
						}
					}
					break;
				case io::EXN_ELEMENT_END:
					if (nodeName == reader->getNodeName())
						pos--;

					if (pos == 0)
						return;

					break;
				}
			}
		}

		void CParticleComponent::setGroupTransform(const core::matrix4& world)
		{
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
			{
				m_data->Groups[i]->setWorldMatrix(world);
			}
		}

		CGroup* CParticleComponent::createParticleGroup()
		{
			return m_data->createGroup();
		}

		CSubGroup* CParticleComponent::createParticleSubGroup(CGroup* group)
		{
			return m_data->createSubGroup(group);
		}

		void CParticleComponent::removeParticleGroup(CGroup* group)
		{
			m_data->removeGroup(group);
		}

		void CParticleComponent::Play()
		{
			CGroup** groups = m_data->Groups.pointer();
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
			{
				std::vector<CEmitter*>& emitter = groups[i]->getEmitters();
				for (CEmitter* e : emitter)
				{
					e->resetTank();
				}
			}
		}

		void CParticleComponent::Stop()
		{
			CGroup** groups = m_data->Groups.pointer();
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
			{
				std::vector<CEmitter*>& emitter = groups[i]->getEmitters();
				for (CEmitter* e : emitter)
				{
					e->stop();
				}
			}
		}

		bool CParticleComponent::IsPlaying()
		{
			CGroup** groups = m_data->Groups.pointer();
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
			{
				if (groups[i]->getNumParticles() > 0)
					return true;
			}

			return false;
		}

		u32 CParticleComponent::getTotalParticle()
		{
			u32 n = 0;

			CGroup** groups = m_data->Groups.pointer();
			for (u32 i = 0, n = m_data->Groups.size(); i < n; i++)
				n += groups[i]->getNumParticles();

			return n;
		}
	}
}