// File Generated by Assets/BuildShader.py - source: [BakeLightVS.d.hlsl : _]
struct VS_INPUT
{
	float4 pos: POSITION;
	float3 norm: NORMAL;
	float4 color: COLOR;
	float2 tex0: TEXCOORD0;
};
struct VS_OUTPUT
{
	float4 pos : SV_POSITION;
	float3 worldNormal: WORLDNORMAL;
	float3 worldPosition: WORLDPOSITION;
	float2 tex0: TEXCOORD0;
};
cbuffer cbPerObject
{
	float4x4 uWorldMatrix;
};
VS_OUTPUT main(VS_INPUT input)
{
	VS_OUTPUT output;
	float2 lightmapUV = input.tex0;
	output.tex0 = input.tex0;
	lightmapUV.y = 1.0 - lightmapUV.y;
	lightmapUV = lightmapUV * 2.0 - float2(1.0, 1.0);
	output.pos = float4(lightmapUV, 0.0, 1.0);
	float4 worldNormal = mul(float4(input.norm, 0.0), uWorldMatrix);
	output.worldNormal = normalize(worldNormal.xyz);
	output.worldPosition = mul(input.pos, uWorldMatrix).xyz;
	return output;
}
