// File Generated by Assets/BuildShader.py - source: [BakeLightVS.d.hlsl : LM,NORMAL_MAP]
struct VS_INPUT
{
	float4 pos: POSITION;
	float3 norm: NORMAL;
	float4 color: COLOR;
	float2 tex0: TEXCOORD0;
	float2 tex1: TEXCOORD1;
	float3 lightmap: LIGHTMAP;
	float3 tangent : TANGENT;
	float3 binormal : BINORMAL;
	float2 data : DATA;
};
struct VS_OUTPUT
{
	float4 pos : SV_POSITION;
	float3 worldNormal: WORLDNORMAL;
	float3 worldPosition: WORLDPOSITION;
	float2 tex0: TEXCOORD0;
	float3 worldTangent: WORLDTANGENT;
	float3 worldBinormal: WORLDBINORMAL;
	float tangentw : TANGENTW;
};
cbuffer cbPerObject
{
	float4x4 uWorldMatrix;
};
VS_OUTPUT main(VS_INPUT input)
{
	VS_OUTPUT output;
	float2 lightmapUV = input.lightmap.xy;
	output.tex0 = input.tex0;
	lightmapUV.y = 1.0 - lightmapUV.y;
	lightmapUV = lightmapUV * 2.0 - float2(1.0, 1.0);
	output.pos = float4(lightmapUV, 0.0, 1.0);
	float4 worldNormal = mul(float4(input.norm, 0.0), uWorldMatrix);
	output.worldNormal = normalize(worldNormal.xyz);
	float4 worldTangent = mul(float4(input.tangent.xyz, 0.0), uWorldMatrix);
	output.worldTangent = normalize(worldTangent.xyz);
	output.worldBinormal = normalize(cross(worldNormal.xyz, worldTangent.xyz));
	output.tangentw = input.data.x;
	output.worldPosition = mul(input.pos, uWorldMatrix).xyz;
	return output;
}
