// File Generated by Assets/BuildShader.py - source: [ColorFS.hlsl : INSTANCING]
struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float2 tex0 : TEXCOORD0;
	float4 worldPosition: WORLDPOSITION;
	float3 worldNormal: WORLDNORMAL;
	float4 color: COLOR;
	float4 specGloss: SPECGLOSS;
};
struct PS_OUTPUT
{
	float4 Diffuse: SV_TARGET0;
	float4 Position: SV_TARGET1;
	float4 Normal: SV_TARGET2;
	float4 SG: SV_TARGET3;
};
PS_OUTPUT main(PS_INPUT input)
{
	PS_OUTPUT output;
	output.Diffuse = input.color;
	output.SG = input.specGloss;
	output.Position = input.worldPosition;
	output.Normal = float4(input.worldNormal, 1.0);
	return output;
}
