// File Generated by Assets/BuildShader.py - source: [SpecularGlossinessVS.hlsl : INSTANCING]
struct VS_INPUT
{
	float4 pos: POSITION;
	float3 norm: NORMAL;
	float4 color: COLOR;
	float2 tex0: TEXCOORD0;
	float3 tangent: TANGENT;
	float3 binormal: BINORMAL;
	float2 data: DATA;
	float4 uvScale: TEXCOORD1;
	float4 uColor: TEXCOORD2;
	float4 uSpecGloss: TEXCOORD3;
	float4x4 worldMatrix: TEXCOORD4;
};
struct VS_OUTPUT
{
	float4 pos : SV_POSITION;
	float2 tex0 : TEXCOORD0;
	float4 worldPosition: WORLDPOSITION;
	float3 worldNormal: WORLDNORMAL;
	float3 worldTangent: WORLDTANGENT;
	float3 worldBinormal: WORLDBINORMAL;
	float tangentw : TANGENTW;
	float4 color: COLOR;
	float2 specGloss: SPECGLOSS;
};
cbuffer cbPerObject
{
	float4x4 uVPMatrix;
	float4x4 uView;
};
VS_OUTPUT main(VS_INPUT input)
{
	VS_OUTPUT output;
	output.color = input.uColor;
	output.specGloss = input.uSpecGloss.xy;
	float4x4 uWorldMatrix = transpose(input.worldMatrix);
	float4 uUVScale = input.uvScale;
	output.tex0 = input.tex0 * uUVScale.xy + uUVScale.zw;
	output.tangentw = input.data.x;
	float4 worldPos = mul(input.pos, uWorldMatrix);
	float4 worldNormal = mul(float4(input.norm, 0.0), uWorldMatrix);
	float4 worldTangent = mul(float4(input.tangent, 0.0), uWorldMatrix);
	output.pos = mul(worldPos, uVPMatrix);
	float4 sampleFragPos = mul(worldPos, uView);
	output.worldPosition = float4(worldPos.xyz, sampleFragPos.z);
	output.worldNormal = normalize(worldNormal.xyz);
	output.worldTangent = normalize(worldTangent.xyz);
	output.worldBinormal = normalize(cross(worldNormal.xyz, worldTangent.xyz));
	return output;
}
