// File Generated by Assets/BuildShader.py - source: [BakeLightVS.d.glsl : LM,NORMAL_MAP]
in vec4 inPosition;
in vec3 inNormal;
in vec4 inColor;
in vec2 inTexCoord0;
in vec3 inLightmap;
in vec3 inTangent;
in vec3 inBinormal;
in vec2 inData;
uniform mat4 uWorldMatrix;
out vec2 varTex0;
out vec3 varWorldPosition;
out vec3 varWorldNormal;
out vec3 vWorldTangent;
out vec3 vWorldBinormal;
out float vTangentW;
void main(void)
{
	vec2 lightmapUV = inLightmap.xy;
	varTex0 = inTexCoord0;
	lightmapUV.y = 1.0 - lightmapUV.y;
	lightmapUV = lightmapUV * 2.0 - vec2(1.0, 1.0);
	varWorldNormal = (uWorldMatrix * vec4(inNormal, 0.0)).xyz;
	varWorldNormal = normalize(varWorldNormal);
	varWorldPosition = (uWorldMatrix * inPosition).xyz;
	vTangentW = inData.x;
	vec4 worldTangent = uWorldMatrix * vec4(inTangent.xyz, 0.0);
	vWorldTangent = normalize(worldTangent.xyz);
	vWorldBinormal = normalize(cross(varWorldNormal, worldTangent.xyz));
	gl_Position = vec4(lightmapUV, 0.0, 1.0);
}
