// File Generated by Assets/BuildShader.py - source: [PostEffectFS.d.glsl : _]
precision mediump float;
precision highp sampler2D;
precision highp sampler2DArray;
uniform sampler2D uTexColor;
uniform vec2 uExposure;
in vec2 varTexCoord0;
in vec4 varColor;
out vec4 FragColor;
const float gamma = 2.2;
const float invGamma = 1.0 / 2.2;
vec3 sRGB(vec3 color)
{
	return pow(color, vec3(gamma));
}
vec3 linearRGB(vec3 color)
{
	return pow(color, vec3(invGamma));
}
void main(void)
{
	vec4 color = texture(uTexColor, varTexCoord0.xy);
	float exposure = uExposure.x;
	FragColor = vec4(linearRGB(exposure * color.rgb), color.a);
}
