// File Generated by Assets/BuildShader.py - source: [BasicVfxFS.d.glsl : SCROLL_Y,LAYER2,SCROLL_LAYER2]
precision mediump float;
uniform sampler2D uTexDiffuse1;
uniform sampler2D uTexDiffuse2;
in vec2 varTexCoord0;
in vec4 varColor;
uniform vec4 uColor;
uniform vec4 uColorIntensity;
uniform vec4 uTime;
out vec4 FragColor;
void main(void)
{
	vec2 uvOffset = vec2(0.0, uTime.x) / 4.0;
	vec4 color1 = texture(uTexDiffuse1, varTexCoord0);
	vec4 color2 = texture(uTexDiffuse2, varTexCoord0 + uvOffset);
	vec4 result = (color1 + color2) * uColor * varColor * uColorIntensity;
	result.a = color1.a * color2.a * uColor.a;
	return result;
}
