// File Generated by Assets/BuildShader.py - source: [BasicVfxVS.d.glsl : SCROLL_Y,LAYER2,SCROLL_LAYER2]
in vec4 inPosition;
in vec4 inColor;
in vec2 inTexCoord0;
uniform mat4 uMvpMatrix;
out vec2 varTexCoord0;
out vec4 varColor;
void main(void)
{
	varTexCoord0 = inTexCoord0;
	varColor = inColor / 255.0;
	gl_Position = uMvpMatrix * inPosition;
}
