// File Generated by Assets/BuildShader.py - source: [BasicVfxFS.d.glsl : SCROLL_UV1]
precision mediump float;
uniform sampler2D uTexDiffuse1;
in vec2 varTexCoord0;
in vec4 varColor;
uniform vec4 uColor1;
uniform vec4 uColorIntensity;
uniform vec4 uTime;
out vec4 FragColor;
void main(void)
{
	vec2 uvOffset = vec2(uTime.x, 0.0) / 4.0;
	vec4 color1 = texture(uTexDiffuse1, varTexCoord0 + uvOffset);
	FragColor = color1 * varColor * uColor1 * uColorIntensity;
}
