// File Generated by Assets/BuildShader.py - source: [BasicVfxFS.d.glsl : SCROLL_UV1,SCROLL_Y]
precision mediump float;
uniform sampler2D uTexDiffuse1;
in vec2 varTexCoord0;
in vec4 varColor;
uniform vec4 uColor;
uniform vec4 uColorIntensity;
uniform vec4 uTime;
out vec4 FragColor;
void main(void)
{
	vec2 uvOffset = vec2(0.0, uTime.x) / 4.0;
	vec4 color1 = texture(uTexDiffuse1, varTexCoord0 + uvOffset);
	FragColor = color1 * varColor * uColor * uColorIntensity;
}
