// File Generated by Assets/BuildShader.py - source: [BasicVfxFS.d.hlsl : SCROLL_UV1,SCROLL_Y]
Texture2D uTexDiffuse1 : register(t0);
SamplerState uTex1Sampler : register(s0);
struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float4 color : COLOR0;
	float2 tex0 : TEXCOORD0;
};
cbuffer cbPerFrame
{
	float4 uColor;
	float4 uColorIntensity;
	float4 uTime;
};
float4 main(PS_INPUT input) : SV_TARGET
{
	float2 uvOffset = float2(0.0, uTime.y) / 4.0;
	float4 color1 = uTexDiffuse1.Sample(uTex1Sampler, input.tex0 + uvOffset);
	return color1 * input.color * uColor * uColorIntensity;
}
