// File Generated by Assets/BuildShader.py - source: [PBRVS.d.glsl : NO_NORMAL_MAP,LM]
in vec4 inPosition;
in vec3 inNormal;
in vec4 inColor;
in vec2 inTexCoord0;
in vec3 inLightmap;
uniform mat4 uMvpMatrix;
uniform mat4 uWorldMatrix;
uniform vec4 uCameraPosition;
uniform vec4 uLightDirection;
uniform vec4 uUVScale;
out vec2 vTexCoord0;
out vec3 vTexCoord1;
out vec3 vWorldNormal;
out vec3 vWorldViewDir;
out vec4 vViewPosition;
out vec3 vWorldPosition;
void main(void)
{
	vTexCoord0 = inTexCoord0 * uUVScale.xy + uUVScale.zw;
	vTexCoord1 = inLightmap;
	vec4 worldPos = uWorldMatrix * inPosition;
	vec4 worldViewDir = normalize(uCameraPosition - worldPos);
	vec4 worldNormal = uWorldMatrix * vec4(inNormal.xyz, 0.0);
	vWorldPosition = worldPos.xyz;
	vWorldNormal = normalize(worldNormal.xyz);
	vWorldViewDir = worldViewDir.xyz;
	vViewPosition = uMvpMatrix * inPosition;
	gl_Position = vViewPosition;
}
