/*
!@
MIT License

Copyright (c) 2019 Skylicht Technology CO., LTD

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
(the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

This file is part of the "Skylicht Engine".
https://github.com/skylicht-lab/skylicht-engine
!#
*/

#include "pch.h"
#include "CGUIExporter.h"
#include "Utils/CStringImp.h"

namespace Skylicht
{
	bool CGUIExporter::save(const char* file, CCanvas* canvas)
	{
		io::IXMLWriter* writeFile = getIrrlichtDevice()->getFileSystem()->createXMLWriter(file);
		if (writeFile == NULL)
			return false;

		writeFile->writeXMLHeader();
		writeFile->writeComment(L"File generated by function CGUIExporter::save");
		writeFile->writeLineBreak();

		CGUIElement* root = canvas->getRootElement();
		CObjectSerializable* object = root->createSerializable();

		if (root->getChilds().size())
		{
			CObjectSerializable* childs = new CObjectSerializable("Childs");
			object->addProperty(childs);
			object->autoRelease(childs);
			addChild(root, childs);
		}

		object->save(writeFile);
		writeFile->drop();

		// save info path file to easy
		char guiInfoFile[256];
		CStringImp::copy(guiInfoFile, file);
		CStringImp::replacePathExt(guiInfoFile, ".txt");
		saveGUIPath(guiInfoFile, object);
		return true;
	}

	void CGUIExporter::saveGUIPath(const char* file, CObjectSerializable* data)
	{
		io::IXMLWriter* writeFileInfo = getIrrlichtDevice()->getFileSystem()->createXMLWriter(file);
		if (writeFileInfo == NULL)
			return;

		writeFileInfo->writeXMLHeader();
		writeFileInfo->writeComment(L"File generated by function CGUIExporter::saveGUIPath");
		writeFileInfo->writeLineBreak();

		writeFileInfo->writeElement(L"nodes", false);
		writeFileInfo->writeLineBreak();

		// skip root element
		CObjectSerializable* childs = data->getProperty<CObjectSerializable>("Childs");
		if (childs)
		{
			CObjectSerializable* canvas = (CObjectSerializable*)childs->getPropertyID(0);

			std::queue<CObjectSerializable*> queue;
			std::queue<std::wstring> queuePath;

			queue.push(canvas);
			queuePath.push(L"");

			std::wstring path, name;

			while (queue.size() > 0)
			{
				CObjectSerializable* obj = queue.front();
				queue.pop();

				std::wstring parentPath = queuePath.front();
				queuePath.pop();

				std::string objName = obj->get("name", std::string("No name")).c_str();
				std::wstring name = CStringImp::convertUTF8ToUnicode(objName.c_str());

				path = parentPath + name;

				writeFileInfo->writeElement(
					L"node", true,
					L"name", name.c_str(),
					L"path", path.c_str()
				);

				writeFileInfo->writeLineBreak();

				path += L"/";

				CObjectSerializable* childs = obj->getProperty<CObjectSerializable>("Childs");
				if (childs)
				{
					u32 numChild = childs->getNumProperty();
					for (u32 i = 0; i < numChild; i++)
					{
						CObjectSerializable* child = (CObjectSerializable*)childs->getPropertyID(i);
						queue.push(child);
						queuePath.push(path);
					}
				}
			}
		}

		writeFileInfo->writeClosingTag(L"nodes");
		writeFileInfo->writeLineBreak();

		writeFileInfo->drop();
	}

	void CGUIExporter::addChild(CGUIElement* parent, CObjectSerializable* parents)
	{
		std::vector<CGUIElement*>& childs = parent->getChilds();
		for (CGUIElement* element : childs)
		{
			CObjectSerializable* object = element->createSerializable();
			parents->addProperty(object);
			parents->autoRelease(object);

			if (element->getChilds().size() > 0)
			{
				CObjectSerializable* childs = new CObjectSerializable("Childs");
				object->addProperty(childs);
				object->autoRelease(childs);
				addChild(element, childs);
			}
		}
	}

	CObjectSerializable* CGUIExporter::createSerializable(CGUIElement* ui)
	{
		CObjectSerializable* object = ui->createSerializable();

		if (ui->getChilds().size())
		{
			CObjectSerializable* childs = new CObjectSerializable("Childs");
			object->addProperty(childs);
			object->autoRelease(childs);
			addChild(ui, childs);
		}

		return object;
	}
}
