// File Generated by Assets/BuildShader.py - source: [SGLitFS.d.hlsl : NO_NORMAL_MAP, NO_TEXTURE, POINTLIGHT]
struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float2 tex0 : TEXCOORD0;
	float4 worldPos: WORLDPOS;
	float3 worldNormal: WORLDNORMAL;
	float3 worldViewDir: WORLDVIEWDIR;
	float3 worldLightDir: WORLDLIGHTDIR;
};
cbuffer cbPerFrame: register(b0)
{
	float4 uLightColor;
	float4 uColor;
	float2 uSpecGloss;
	float2 uLightMul;
	float4 uCamPosition;
	float4 uLightIndex;
	float4 uSHConst[4];
};
struct PointLight {
	float4 Position;
	float4 Attenuation;
	float4 Direction;
	float4 Color;
};
cbuffer uListLights: register(b1)
{
	PointLight Lights[200]: packoffset(c0);
};
static const float gamma = 2.2;
static const float invGamma = 1.0 / 2.2;
float3 sRGB(float3 color)
{
	return pow(color, gamma);
}
float3 linearRGB(float3 color)
{
	return pow(color, invGamma);
}
float3 shAmbient(float3 n)
{
	float3 ambientLighting = uSHConst[0].xyz +
		uSHConst[1].xyz * n.y +
		uSHConst[2].xyz * n.z +
		uSHConst[3].xyz * n.x;
	return ambientLighting * 0.75;
}
float3 pointlight(
	const float3 position,
	const float3 normal,
	const float3 camPosition,
	const float4 lightColor,
	const float3 lightPosition,
	const float4 lightAttenuation,
	const float spec,
	const float gloss,
	const float3 specColor)
{
	float3 direction = lightPosition - position;
	float distance = length(direction);
	float attenuation = max(0.0, 1.0 - (distance * lightAttenuation.y)) * lightColor.a;
	float3 lightDir = normalize(direction);
	float NdotL = max(0.0, dot(lightDir, normal));
	float3 v = camPosition - position;
	float3 viewDir = normalize(v);
	float3 H = normalize(direction + viewDir);
	float NdotE = max(0.0,dot(normal, H));
	float specular = pow(NdotE, 10.0 + 100.0 * gloss) * spec;
	return (lightColor.rgb * NdotL + specular * specColor) * attenuation;
}
static const float PI = 3.1415926;
float4 main(PS_INPUT input) : SV_TARGET
{
	float4 diffuseMap = uColor;
	float3 specMap = float3(uSpecGloss, 1.0);
	float3 n = input.worldNormal;
	float3 ambientLighting = shAmbient(n);
	ambientLighting = sRGB(ambientLighting);
	float3 diffuseColor = sRGB(diffuseMap.rgb);
	float3 lightColor = sRGB(uLightColor.rgb);
	float spec = specMap.r;
	float gloss = specMap.g;
	float3 specularColor = float3(0.5, 0.5, 0.5);
	float NdotL = max(dot(n, input.worldLightDir), 0.0);
	float3 directionalLight = NdotL * lightColor;
	PointLight light = Lights[(int)uLightIndex.x];
	directionalLight += pointlight(
		input.worldPos.xyz,
		n,
		uCamPosition.xyz,
		light.Color,
		light.Position.xyz,
		light.Attenuation,
		spec,
		gloss,
		specularColor);
	light = Lights[(int)uLightIndex.y];
	directionalLight += pointlight(
		input.worldPos.xyz,
		n,
		uCamPosition.xyz,
		light.Color,
		light.Position.xyz,
		light.Attenuation,
		spec,
		gloss,
		specularColor);
	float3 color = directionalLight * diffuseColor * 0.3 * uLightMul.y;
	float3 H = normalize(input.worldLightDir + input.worldViewDir);
	float NdotE = max(0.0,dot(n, H));
	float specular = pow(NdotE, 10.0 + 100.0 * gloss) * spec;
	color += specular * specularColor * uLightMul.x;
	color += ambientLighting * diffuseColor / PI;
	return float4(color, diffuseMap.a);
}
